## stack():    Join a sequence of arrays along a new axis.沿着新轴加入一系列阵列。
## vstack():  Stack arrays in sequence vertically (row wise).垂直的
## hstack():  Stack arrays in sequence horizontally (column wise).水平的
## concatenate():   Join a sequence of arrays along an existing axis.沿着一个现有的轴加入数组。

In [1]:
import numpy as np

# stack

In [2]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
arrays

[array([[ 0.00236369, -1.30202802,  0.79611703, -0.19320406],
        [ 0.43582054, -0.61603809, -1.21399513,  0.32133532],
        [ 0.56888128,  0.47735101, -0.07873614, -1.32670695]]),
 array([[ 1.11279442, -0.56372406, -0.17004647, -1.04008354],
        [-0.1551555 ,  0.25890959, -0.29976097,  0.53740687],
        [ 0.67163674,  0.19284107,  0.37133895, -1.39977144]]),
 array([[-1.2334446 ,  0.89299408,  1.11147777, -1.02085542],
        [-0.1239883 , -0.32621232, -1.63129531, -0.8262432 ],
        [ 1.50672522, -0.17284408,  1.31218277, -1.03845642]]),
 array([[ 0.70053809, -2.72096909,  1.56244688, -0.99104775],
        [-1.33558036, -1.01058772,  0.49069439, -0.98685965],
        [-0.17069287,  1.71674066,  0.05745742,  1.40505941]]),
 array([[-0.50872513, -0.36629257,  0.37640496, -1.70816558],
        [-1.59810083,  0.71240104, -0.06020049, -0.31714147],
        [ 0.23619526,  1.63983439, -0.93307694,  2.10185592]]),
 array([[ 2.63025964,  0.0495838 ,  1.4144833 , -1.25712258]

In [3]:
np.stack(arrays, axis=0).shape

(10L, 3L, 4L)

In [4]:
np.stack(arrays, axis=1).shape

(3L, 10L, 4L)

In [5]:
np.stack(arrays, axis=2).shape

(3L, 4L, 10L)

In [6]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
a, b

(array([1, 2, 3]), array([2, 3, 4]))

In [7]:
a.shape, b.shape

((3L,), (3L,))

In [12]:
ab_0 = np.stack((a, b))
ab_0

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
ab_0.shape

(2L, 3L)

In [14]:
ab_1 = np.stack((a, b), axis=1)
ab_1

array([[1, 2],
       [2, 3],
       [3, 4]])

In [15]:
ab_1.shape

(3L, 2L)

# vstack（垂直的） 等价于np.concatenate(tup, axis=0)
## 我给个小总结：vstack的堆砌作用就是增加行数

In [16]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
a, b

(array([1, 2, 3]), array([2, 3, 4]))

In [17]:
a.shape, b.shape

((3L,), (3L,))

In [18]:
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [22]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
print 'a: ',a
print 'b: ',b

a:  [[1]
 [2]
 [3]]
b:  [[2]
 [3]
 [4]]


In [23]:
a.shape, b.shape

((3L, 1L), (3L, 1L))

In [25]:
ab = np.vstack((a, b))
ab

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

In [26]:
ab.shape

(6L, 1L)

# hstack（水平方向）等价于 np.concatenate(tup, axis=1)
## 我给个小总结就是：hstack的堆砌作用就是增加列数

In [27]:
a = np.array((1, 2, 3))
b = np.array((2, 3, 4))
a, b

(array([1, 2, 3]), array([2, 3, 4]))

In [28]:
a.shape, b.shape

((3L,), (3L,))

In [29]:
np.hstack((a, b))

array([1, 2, 3, 2, 3, 4])

In [30]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
a, b

(array([[1],
        [2],
        [3]]), array([[2],
        [3],
        [4]]))

In [31]:
a.shape, b.shape

((3L, 1L), (3L, 1L))

In [32]:
np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

# concatenate

In [33]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a, b

(array([[1, 2],
        [3, 4]]), array([[5, 6]]))

In [34]:
a.shape, b.shape

((2L, 2L), (1L, 2L))

In [35]:
np.concatenate((a, b), axis=0)  #等价于vstack 增加了行数

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
np.concatnate((a, b), axis=1)   #b的行数和a的行数不相等 所以不能堆砌

AttributeError: 'module' object has no attribute 'concatnate'

In [38]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])